font:  # 主题字体配置
  font_family: Segoe UI,SegoeUI,Helvetica Neue,Helvetica,Arial,sans-serif

index:
  slogan:
    text: "竹杖芒鞋轻胜马，一蓑烟雨任平生。"



about:
  enable: true
  banner_img: /img/default.png
  banner_img_height: 60
  banner_mask_alpha: 0.3
  avatar: /img/avatar.png
  name: "旺旺雪饼"
  intro: "旺旺雪饼的主页"
  # 更多图标可从 https://hexo.fluid-dev.com/docs/icon/ 查找，`class` 代表图标的 css class，添加 `qrcode` 后，图标不再是链接而是悬浮二维码
  # More icons can be found from https://hexo.fluid-dev.com/docs/en/icon/  `class` is the css class of the icon. If adding `qrcode`, The icon is no longer a link, but a hovering QR code
  icons:
    - { class: "iconfont icon-github-fill", link: "https://github.com/ww-xb", tip: "GitHub" }
    - { class: "iconfont icon-wechat-fill", qrcode: "/img/wechat.png" }
    - { class: "iconfont icon-mail", link: "mailto://horanzuo@gmail.com" }

navbar:
  blog_title: "旺旺雪饼"
  menu:
    - { key: "home", link: "/", icon: "iconfont icon-home-fill" }
    - { key: "archive", link: "/archives/", icon: "iconfont icon-archive-fill" }
    - { key: "tag", link: "/tags/", icon: "iconfont icon-tags-fill" }
    - { key: "about", link: "/about/", icon: "iconfont icon-user-fill" }